# Generated by Django 5.2.4 on 2025-07-04 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='installs',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='app',
            name='size',
            field=models.IntegerField(),
        ),
    ]
